### ISSUE TITLE
Does not work well with dark theme

### ISSUE THREAD

**Issue by targodan** [hasherezade/ida_ifl#14]
Great plugin, sadly it does not work well with the dark theme.

The text in the table is barely readable and it somehow seems to mess with the theme of the disassembly view as well.

How to reproduce:
1. Click Options -> Colors and select theme "dark". Click Ok. (I did this way *before* installing the plugin)
2. Install the plugin
3. Open the view via View -> IFL

Strangely even applying the dark theme again does not set the disassembly view theme correctly.

**Comment by hasherezade** [comment]
Thank you for reporting! I will fix it as soon as I get some free time.

**Comment by GH-Rake** [comment]
Where has this plugin been all my life?  Can't live without it now

This is just a quick fix for dark mode, doesn't look pretty but at least you can read the text in the meantime.

Find and replace:
QtGui.QColor("khaki") -> QtGui.QColor("black")
QtGui.QColor("orange") -> QtGui.QColor("orangered")
QtGui.QColor("lightblue") -> QtGui.QColor("blue")

![image](https://user-images.githubusercontent.com/15186628/95270573-c7845b00-0809-11eb-8563-2c72d71de13a.png)

**Comment by hasherezade** [comment]
It looks like this with my latest fixes:

**dark:**

![ifl_dark](https://user-images.githubusercontent.com/3115348/103661765-60dd1d80-4f6f-11eb-8a78-ec86443f6b75.png)

**light:**

![ifl_light](https://user-images.githubusercontent.com/3115348/103661851-7a7e6500-4f6f-11eb-9b0d-b5e47b81b0d4.png)

**Comment by hasherezade** [comment]
I made another update, hopefully it is better!
+ https://github.com/hasherezade/ida_ifl/releases/tag/v1.4.2.1 (Python3)
+ https://github.com/hasherezade/ida_ifl/releases/tag/v1.3.7.1 (Python2)

Preview:

**dark**

![dark1](https://user-images.githubusercontent.com/3115348/103719104-9bbf6f80-4fc8-11eb-8d2e-8be71041dfbd.png)

**light**

![light1](https://user-images.githubusercontent.com/3115348/103719112-9eba6000-4fc8-11eb-8e4d-da83b8dce541.png)

//cc @targodan
