### ISSUE TITLE
IDA7.0 - Python2.x support?

### ISSUE THREAD

**Issue by lawiet47** [hasherezade/ida_ifl#15]
Any support for IDA v <= 7.0? Doesn't seem to be compatible with python2.x.

I've already tried to convert it back to python2 to import it to IDA 7.0 but been seeing weird error messages

```
File "C:/Program Files/IDA 7.0/plugins/ifl.py", line 1304, in <module>
    PLUGIN_ENTRY().init()

  File "C:/Program Files/IDA 7.0/plugins/ifl.py", line 1282, in init
   u 'Opens Interactive Function List Pane')

  File "C:\Program Files\IDA 7.0\python\ida_kernwin.py", line 1545, in __init__
    this = _ida_kernwin.new_action_desc_t(*args)

TypeError: in method 'new_action_desc_t', argument 2 of type 'char const *'
```

**Comment by hasherezade** [comment]
Check the branch [python2](https://github.com/hasherezade/ida_ifl/tree/python2) and earlier releases, i.e.:
+ https://github.com/hasherezade/ida_ifl/releases/tag/v1.3.6

**Comment by lawiet47** [comment]
Amazing, thanks
