### ISSUE TITLE
Does not work for me in IDA 7.0

### ISSUE THREAD

**Issue by Shurf** [hasherezade/ida_ifl#4]
seems to work if PLUGIN_ENTRY() returns funclister_t() instead of funclister_t().init()

**Comment by hasherezade** [comment]
this is strange - for me both versions works: with init() and without. I can remove the init() as well if it creates issues, but I want to know where this problem comes from. can you share something more about the error that you are getting?

**Comment by Shurf** [comment]
Both x86 and x64 versions of IDA tell me this in output:
C:\Program Files\IDA 7.0\plugins\ifl.py: C:\Program Files\IDA 7.0\plugins\ifl.py: PLUGIN_ENTRY() must return an object!

Sorry, I do not have any experience with writing IDA plugins, so I do not know what additional information I can provide. I can try to debug it if you tell me what should I look for.

**Comment by hasherezade** [comment]
Ok, thank you. Please let me know if now everything works for you.

**Comment by Shurf** [comment]
Works for me now, thank you

**Comment by hasherezade** [comment]
Thank you for reporting the issue!
