### ISSUE TITLE
Live search extremely slow

### ISSUE THREAD

**Issue by fireundubh** [hasherezade/ida_ifl#5]
Can you add a toggle to enable/disable live search? The StringCluster plugin, for example, has a checkbox for toggling live search. When toggled off, pressing Enter executes the query.

**Comment by hasherezade** [comment]
ok, good idea. I will add it.

**Comment by hasherezade** [comment]
I added, please let me know if this is what you needed: https://github.com/hasherezade/ida_ifl/tree/live_filter

**Comment by hasherezade** [comment]
please let me know if this is what you meant

**Comment by fireundubh** [comment]
Perfect! Excellent work. Thank you!
