### ISSUE TITLE
Switch to python 3

### ISSUE THREAD

**Issue by hasherezade** [hasherezade/ida_ifl#9]
Starting from version 7.4, IDA uses Python 3, so IFL should be switched to this version.

**Comment by nazywam** [comment]
I've started working on it in https://github.com/nazywam/ida_ifl/pull/1
Seems to work fine on IDA7.4 + python3 but it will obviously need some more testing.

I also added support for mypy type hints but I'm still looking for a smart way to test it in IDA context.

**Comment by hasherezade** [comment]
I tested your Python3 version with the latest IDA (7.5) and everything looks fine. Feel free to send me a pull request.
